[build]
  publish = "exampleSite/public"
  command = '''hugo -s exampleSite --config "exampleSite/config.toml" \
&& hugo -s exampleSite --config "exampleSite/config.toml,exampleSite/config-original.toml"'''

[build.environment]
  HUGO_VERSION = "0.115"
  HUGO_THEME = "repo"
  HUGO_THEMESDIR = "/opt/build"

# [context.production.environment]
#   HUGO_VERSION = "0.115"

# [context.deploy-preview.environment]
#   HUGO_VERSION = "0.115"

# [context.branch-deploy.environment]
#   HUGO_VERSION = "0.115"
  
